# Generated by Django 6.1.1 on 2026-09-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('slug', models.SlugField(unique=True, verbose_name='Blog title')),
                ('image', models.ImageField(blank=True, default='blog_default_pic/', upload_to='blog_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(blank=True, default='project_default_pic/', upload_to='project_list/', verbose_name='Image')),
                ('text', models.TextField(max_length=50, verbose_name='Text')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='Live Url')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub Url')),
                ('date', models.DateField(verbose_name='Date')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='main.tags', verbose_name='Technologies')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
