# Generated by Django 6.1.1 on 2026-09-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_list/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(max_length=100, verbose_name='Text'),
        ),
    ]
